### ISSUE TITLE
"await visit()" becomes "await await visit()"

### ISSUE THREAD

**Issue by Turbo87** [simonihmig/ember-native-dom-helpers-codemod#17]
<img width="628" alt="bildschirmfoto 2017-06-09 um 21 34 11" src="https://user-images.githubusercontent.com/141300/26991618-684eabca-4d5b-11e7-84b8-06fc94196bd0.png">

**Comment by simonihmig** [comment]
Uh, not so good (_"Doppelt hält besser"_ does not apply here I guess). Probably all other cases where ` await` is added will be affected by this as well, if the Promise-returning helper has been flagged as `await` even before running the codemod. Will have a look...

**Comment by simonihmig** [comment]
Released as 0.1.3
