### ISSUE TITLE
Doesn't account for selectors as variables within `containsJQuerySelectorExtension`

### ISSUE THREAD

**Issue by scalvert** [simonihmig/ember-native-dom-helpers-codemod#27]
Currently, if a jQuery selector is represented via a variable:

```js
const SOME_SELECTOR = '.my-class:first';

$(SOME_SELECTOR).click();
```

the codemod will optimistically transform this to:

```js
const SOME_SELECTOR = '.my-class:first';

await click(SOME_SELECTOR);
```

This will result in a Syntax Error when running the tests, as `querySelector` can't handle the custom pseudo selectors sizzle supports.

A conservative approach would be to noop if encountering a selector in a variable.

**Comment by simonihmig** [comment]
Thanks for reporting! It might be possible to check the value of the variable, so to only opt out of transforming this when the value contains a non-standard selector. Will have to give this a try...

**Comment by scalvert** [comment]
This is exactly what I was thinking too. LMK if you want help.
