### ISSUE TITLE
jQuery `.html(string)` calls get erroneously transformed.

### ISSUE THREAD

**Issue by scalvert** [simonihmig/ember-native-dom-helpers-codemod#31]
When running the codemod, calls to

```js
this.$('.foo').html('some string');
```

get erroneously transformed to

```js
find('.foo').innerHTML;
```

Basically, this transform ends up lossy for `.html()` calls with parameters (when setting values).

**Comment by simonihmig** [comment]
@scalvert Thanks for reporting! Do you plan to fix this? I can do as well, just want to prevent accidentally doing the same work twice here...

**Comment by scalvert** [comment]
I can totally fix this. I just didn't get around to it yesterday. I'll work on it now.
