### ISSUE TITLE
Running the tests - need specific environment setup?

### ISSUE THREAD

**Issue by snewcomer** [simonihmig/ember-native-dom-helpers-codemod#41]
Having into a problem with running the test suite.  Getting the error below.  Seems like it is using an older version of babel locally.  Tried node 6.12, 9.4, 7.9, 8.0, etc.  Is there some environment specifics I am missing that you know of?

```
ReferenceError: [BABEL] /Users/snewcomer/Github/ember-test-helpers-codemod/__tests__/acceptance-test.js: Unknown option: direct.presets
```

**Comment by simonihmig** [comment]
That is strange, because Babel is not used at all here!? 😳 

There is no frontend code, just plain node.js!? Maybe some misconfiguration of your local system?

**Comment by snewcomer** [comment]
The command is simply `npm test`, correct?  The Jest version is v22.1.4 and here is a screenshot of jscodeshift --version.

<img width="252" alt="screen shot 2018-01-30 at 10 03 43 pm" src="https://user-images.githubusercontent.com/7374640/35607533-7d3a4fbe-0609-11e8-915c-2ea9fa1bd585.png">

**Comment by simonihmig** [comment]
> The command is simply npm test, correct?

Yes. I use an older version. Will have to update and try myself...

**Comment by snewcomer** [comment]
Closing.  Can run tests for this and ember-test-helpers-codemod now.
