### ISSUE TITLE
Supporting glob filepaths

### ISSUE THREAD

**Issue by nlfurniss** [simonihmig/ember-native-dom-helpers-codemod#44]
Currently following the readme's instructions, providing globs doesn't work.

Doesn't work
`ember-native-dom-helpers-codemod --type=acceptance path/to/files/upoad-*`

Does work
`jscodeshift path/to/files/upload-* -t /usr/local/lib/node_modules/ember-native-dom-helpers-codemod/index.js --type=acceptance`

So I'm either doing it wrong, or the order of the args needs to change in [ember-native-dom-helpers-codemod.js](https://github.com/simonihmig/ember-native-dom-helpers-codemod/blob/master/bin/ember-native-dom-helpers-codemod.js#L12). Let me know, will be happy to open a PR

**Comment by simonihmig** [comment]
> So I'm either doing it wrong, or the order of the args needs to change in ember-native-dom-helpers-codemod.js. Let me know, will be happy to open a PR

Not sure, maybe you are right! Feel free to try it out, a PR would certainly by highly appreciated!
