### ISSUE TITLE
Should use `triggerKeyEvent` instead of `keyEvent`

### ISSUE THREAD

**Issue by wagenet** [simonihmig/ember-native-dom-helpers-codemod#46]

**Comment by simonihmig** [comment]
I don't see a `triggerKeyEvent` helper: https://github.com/cibernox/ember-native-dom-helpers#helpers.

In case you want to use the "offical" helpers from `@ember/test-helpers`, this is for you: https://github.com/simonihmig/ember-test-helpers-codemod

**Comment by wagenet** [comment]
Yes, I was confused by the similarity. What role does this repo have long term?

**Comment by simonihmig** [comment]
> What role does this repo have long term?

Yes, so I think it will  be superseded by the other, as `e-n-d-h` has also started to issue deprecation warnings, so this codemod can also be regarded as kind of deprecated. People might still want to use it, if they can't migrate to the new testing APIs right away. 

I added a note to the Readme recently, that links to the other codemod.

**Comment by wagenet** [comment]
Thanks!
